### ISSUE TITLE
Login Front-End

### ISSUE THREAD

**Issue by darshilpatel32** [tykm/tinder-for-movies#7]

**Comment by DezChap** [comment]
Tyler and I worked on this together a couple days ago. He pushed his version of the first part of the google-oauth so we just had to work from there. I wrote the rest of the code for the login in the google-oauth branch. We both have developer keys so everything has been tested and is working as of right now. I was able to have a useState hold the email and names which then is emitted to the back-end. There is also a success/fail of login check where if it is successful it will go onto the next js component (Genres.js), but if it fails right now we just have it give a window-alert. I think we agreed that for now the login page is done and has all the main functionality it needs to login a user and take in there information.
